---
- name: Ensure configuration path exist
  ansible.builtin.file:
    dest: "{{ systemd_overrides_config_file_path }}/{{ item }}.service.d/"
    state: directory
    owner: root
    group: root
    mode: "0644"
  loop: "{{ systemd_overrides_unit }}"

- name: Ensure configuration
  ansible.builtin.template:
    dest: "{{ systemd_overrides_config_file_path }}/{{ item }}.service.d/z_override.conf"
    src: z_override.conf.j2
    owner: root
    group: root
    mode: "0644"
  loop: "{{ systemd_overrides_unit }}"
  register: systemd_overrides_config_changed

- name: Ensure configuration
  ansible.builtin.template:
    dest: "{{ systemd_overrides_config_file_path }}/redis.service.d/z_override.conf"
    src: redis_override.conf.j2
    owner: root
    group: root
    mode: "0644"

- name: Ensure configuration path exist
  ansible.builtin.file:
    dest: "{{ systemd_overrides_config_file_path }}/systemd-tmpfiles-clean.timer.d/"
    state: directory
    owner: root
    group: root
    mode: "0644"

- name: Ensure configuration
  ansible.builtin.template:
    dest: "{{ systemd_overrides_config_file_path }}//systemd-tmpfiles-clean.timer.d/z_override.conf"
    src: z_override.conf.j2
    owner: root
    group: root
    mode: "0644"
  register: systemd_overrides_config_changed

- name: Force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: true
  when: systemd_overrides_config_changed | bool
