---
# Variable setup.
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Define redis_package.
  ansible.builtin.set_fact:
    redis_package: "{{ __redis_package }}"
  when: redis_package is not defined

- name: Ensure Redis configuration dir exists.
  ansible.builtin.file:
    path: "{{ redis_conf_path | dirname }}"
    state: directory
    mode: "{{ redis_conf_dir_mode }}"

- name: Configure sysctl for redis
  ansible.builtin.include_tasks: sysctl.yml

- name: Setup/install task
  ansible.builtin.include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Ensure Redis is configured.
  ansible.builtin.template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: "{{ redis_conf_mode }}"
    owner: redis
  notify: Restart redis

- name: Ensure Redis is running and enabled on boot.
  ansible.builtin.service:
    name: "{{ redis_daemon }}"
    state: started
    enabled: true
