---
- name: Sysctl configured.
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value.value }}"
    state: present
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/99-redis.conf
  loop: "{{ lookup('dict', redis_sysctl_config) }}"

- name: Install sysfsutils for disabling transparent huge pages
  ansible.builtin.package:
    name: sysfsutils
    state: present

- name: Disable transparent huge pages for redis performance - persistent change
  ansible.builtin.lineinfile:
    path: /etc/sysfs.d/thp.conf
    create: true
    line: "kernel/mm/transparent_hugepage/enabled = madvise"
    owner: root
    group: root
    mode: '0644'
  register: sysfsconf_changed
  notify: Restart sysfsutils
