---
- name: Ensure php tmp dirs exist
  ansible.builtin.template:
      dest: "/etc/tmpfiles.d/{{ domain }}.conf"
      src: tmpfiles_php_default.j2
      backup: true
      mode: "0640"
  when: domain == "default"

- name: Ensure php tmp dirs exist
  ansible.builtin.template:
      dest: "/etc/tmpfiles.d/{{ domain }}.conf"
      src: tmpfiles_php.j2
      backup: true
      mode: "0640"
  when: domain != "default"

# - name: Ensure mysql tmp dirs exist
#  ansible.builtin.template:
#      dest: /etc/tmpfiles.d/mysqld.conf
#      src: tmpfiles_mysqld.j2
#      backup: true
#      mode: "0640"
#  notify: Create tmpfiles

# - name: Ensure mysql tmp dirs exist
#  ansible.builtin.template:
#      dest: /etc/tmpfiles.d/push.conf
#      src: tmpfiles_push.j2
#      backup: true
#      mode: "0640"
#  notify: Create tmpfiles

- name: Create tmpfiles
  ansible.builtin.command: systemd-tmpfiles --create
  changed_when: true
