---
systemd_overrides_config_file_path: /etc/systemd/system/
systemd_overrides_unit:
   - apache2
   - httpd
   - memcached
   - mysql
   - mysqld
   - mariadb
   - nginx
   - php-fpm
   - php{{ php_default_version_debian }}-fpm
   - php{{ php_default_version_debian }}-fpm-xdebug
   - redis
   - redis-server
   - transformer
   - unattended-upgrades

systemd_overrides_redis_group: "{{ nginx_user }}"
