---
- name: Get MySQL version.
  ansible.builtin.command: 'mysql --version'
  register: mysql_cli_version
  changed_when: false
  check_mode: false

- name: Verify mysql include directory exists.
  ansible.builtin.file:
    path: "{{ mysql_config_include_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: mysql_config_include_files | length

- name: Copy my.cnf global MySQL configuration.
  ansible.builtin.template:
    src: my.cnf.j2
    dest: "{{ mysql_config_include_dir }}/x_server.cnf"
    owner: root
    group: root
    mode: "0644"
    trim_blocks: true
    lstrip_blocks: true
  notify: restart mysql

- name: Copy my.cnf override files into include directory.
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ mysql_config_include_dir }}/{{ item.src | basename }}"
    owner: root
    group: root
    mode: "0644"
    force: "{{ item.force | default(False) }}"
  with_items: "{{ mysql_config_include_files }}"
  notify: restart mysql

- name: Add [mysqld] in z_bx_custom.cnf file
  ansible.builtin.lineinfile:
    path: "{{ mysql_config_include_dir }}/z_bx_custom.cnf"
    line: "[mysqld]"
    create: true
    state: present
    owner: root
    group: root
    mode: "0644"

- name: Verify mysql log directory exists.
  ansible.builtin.file:
    path: "{{ mysql_log_dir }}"
    state: directory
    owner: mysql
    group: "{{ mysql_log_file_group }}"
    mode: "2750"

- name: Create slow query log file (if configured).
  ansible.builtin.command: "touch {{ mysql_slow_query_log_file }}"
  args:
    creates: "{{ mysql_slow_query_log_file }}"
  when: mysql_slow_query_log_enabled

- name: Create datadir if it does not exist
  ansible.builtin.file:
    path: "{{ mysql_datadir }}"
    state: directory
    owner: mysql
    group: mysql
    mode: "0755"
    setype: mysqld_db_t

- name: Set ownership on slow query log file (if configured).
  ansible.builtin.file:
    path: "{{ mysql_slow_query_log_file }}"
    state: file
    owner: mysql
    group: "{{ mysql_log_file_group }}"
    mode: "0640"
  when: mysql_slow_query_log_enabled

- name: Create error log file (if configured).
  ansible.builtin.command: "touch {{ mysql_log_error }}"
  args:
    creates: "{{ mysql_log_error }}"
  when:
    - mysql_log | default(true)
    - mysql_log_error | default(false)
  tags: ['skip_ansible_galaxy']

- name: Set ownership on error log file (if configured).
  ansible.builtin.file:
    path: "{{ mysql_log_error }}"
    state: file
    owner: mysql
    group: "{{ mysql_log_file_group }}"
    mode: "0640"
  when:
    - mysql_log | default(true)
    - mysql_log_error | default(false)
  tags: ['skip_ansible_galaxy']

- name: Ensure MySQL is started and enabled on boot.
  ansible.builtin.service:
    name: "{{ mysql_daemon }}"
    state: started
    enabled: "{{ mysql_enabled_on_startup }}"
  register: mysql_service_configuration

- name: Wait for MySQL socket file
  ansible.builtin.wait_for:
    path: "{{ mysql_socket }}"
    timeout: 60
