---
- name: Delete the site {{ site }}
  hosts: localhost
  connection: local
  become: yes
  gather_facts: no
  tasks:
    - name: Deliting site dir {{ full_path_site }}
      file:
        name: "{{ full_path_site }}"
        state: absent

    - block:

        - name: Installing of python3-pymysql
          apt:
            name: python3-pymysql
            state: present

        - name: Deliting data base {{ db_name }}
          mysql_db:
            name: "{{ db_name }}"
            state: absent

        - name: Deliting database user {{ db_user }}
          mysql_user:
            name: "{{ db_user }}"
            state: absent

        - name: Deliting cron task
          cron:
            name: Adding cron bitrix agents site {{ site }}
            user: "{{ user_server_sites }}"
            state: absent

      when: type == "full"

    - name: Rename Nginx config {{ site }}.conf
      file:
        name: "{{ path_nginx_sites_conf }}/{{ site }}.conf"
        state: absent

    - name: Delete nginx config link {{ site }}.conf
      file:
        name: "{{ path_nginx_sites_enabled }}/{{ site }}.conf"
        state: absent

    - name: Rename Apache config {{ site }}.conf
      file:
        name: "{{ path_apache_sites_conf }}/{{ site }}.conf"
        state: absent

    - name: Restarting Nginx
      systemd:
        name: "{{ service_nginx_name }}"
        state: reloaded

    - name: Restarting Apache
      systemd:
        name: "{{ service_apache_name }}"
        state: reloaded
