---
- name: Editing of the site {{ domain }}
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  roles:
    - role: edit_site
    - role: get_lets_encrypt_certificate
      vars:
        path_site: "{{ path_sites }}/{{ domain }}"
        is_www: "{{ ssl_lets_encrypt_www }}"
        email: "{{ ssl_lets_encrypt_email }}"
      when: ssl_lets_encrypt == "Y"
    - role: geerlingguy.php
      vars:
        php_fpm_listen: "/run/php/php{{ php_version }}-{{ php_fpm_pool_user }}-fpm.sock"
        php_use_managed_bitrixenv_ini: false
        php_enable_php_fpm: true
        php_fpm_pools:
          - pool_name: "{{ php_version }}-{{ php_fpm_pool_user }}"
            pool_config_filename: "{{ php_fpm_pool_user }}.conf"
            pool_ansible.builtin.template: www.conf.j2
            pool_listen: "{{ php_fpm_listen }}"
            pool_listen_allowed_clients: "{{ php_fpm_listen_allowed_clients }}"
            php_fpm_listen_owner: www-data
            php_fpm_listen_group: www-data
            pool_pm: ondemand
            pool_pm_max_children: "{{ php_fpm_pm_max_children }}"
            pool_pm_start_servers: "{{ php_fpm_pm_start_servers }}"
            pool_pm_min_spare_servers: "{{ php_fpm_pm_min_spare_servers }}"
            pool_pm_max_spare_servers: "{{ php_fpm_pm_max_spare_servers }}"
            pool_pm_max_requests: "{{ php_fpm_pm_max_requests }}"
            pool_pm_status_path: "{{ php_fpm_pm_status_path }}"
            pool_php_flag_display_errors: "{{ php_fpm_php_flag_display_errors }}"
            pool_php_admin_value_error_log: "{{ php_fpm_php_admin_value_error_log }}"
            pool_php_admin_flag_log_errors: "{{ php_fpm_php_admin_flag_log_errors }}"
          - pool_name: "{{ php_version }}-{{ php_fpm_pool_user }}-xdebug"
            pool_config_filename: "{{ php_fpm_pool_user }}.xdebug"
            pool_ansible.builtin.template: www.conf.j2
            pool_listen: "{{ php_fpm_listen }}-xdebug"
            pool_listen_allowed_clients: "{{ php_fpm_listen_allowed_clients }}"
            php_fpm_listen_owner: www-data
            php_fpm_listen_group: www-data
            pool_pm: ondemand
            pool_pm_max_children: "{{ php_fpm_pm_max_children }}"
            pool_pm_start_servers: "{{ php_fpm_pm_start_servers }}"
            pool_pm_min_spare_servers: "{{ php_fpm_pm_min_spare_servers }}"
            pool_pm_max_spare_servers: "{{ php_fpm_pm_max_spare_servers }}"
            pool_pm_max_requests: "{{ php_fpm_pm_max_requests }}"
            pool_pm_status_path: "{{ php_fpm_pm_status_path }}"
            pool_php_flag_display_errors: "{{ php_fpm_php_flag_display_errors }}"
            pool_php_admin_value_error_log: "{{ php_fpm_php_admin_value_error_log }}"
            pool_php_admin_flag_log_errors: "{{ php_fpm_php_admin_flag_log_errors }}"
      when:
        - user_server_sites != "www-data"

  post_tasks:
    - name: Reload php-fpm
      ansible.builtin.service:
        name: "php{{ php_version }}-fpm"
        state: reloaded
        enabled: true
        daemon_reload: true
      when: not php_enable_php_fpm_xdebug | bool
    - name: Reload php-fpm-xdebug
      ansible.builtin.service:
        name: "php{{ php_version }}-fpm-xdebug"
        state: reloaded
        enabled: true
        daemon_reload: true
      when: php_enable_php_fpm_xdebug | bool
