---
- name: Setup sysctl
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

#  pre_tasks:
#    - name: Load tcp_bbr module
#      community.general.modprobe:
#        name: tcp_bbr
#        state: present
#        persistent: present

  roles:
    - role: buluma.sysctl
      vars:
        sysctl_file: /etc/sysctl.d/50-vmmenu.conf
        sysctl_items:
          - name: net.ipv4.ip_forward
            value: 0
          - name: net.ipv4.conf.all.rp_filter
            value: 1
          - name: net.ipv4.conf.default.rp_filter
            value: 1
          - name: net.ipv4.conf.all.accept_redirects
            value: 0
          - name: net.ipv4.conf.all.secure_redirects
            value: 0
          - name: net.ipv4.conf.all.send_redirects
            value: 0
          - name: net.ipv4.conf.default.accept_redirects
            value: 0
          - name: net.ipv4.conf.default.secure_redirects
            value: 0
          - name: net.ipv4.conf.default.send_redirects
            value: 0
          - name: net.ipv4.icmp_echo_ignore_broadcasts
            value: 1
          - name: net.ipv4.icmp_ignore_bogus_error_responses
            value: 1
          - name: net.ipv4.tcp_max_syn_backlog
            value: 4096
          - name: net.core.netdev_max_backlog
            value: 1000
          - name: net.core.somaxconn
            value: 8151
          - name: net.ipv4.tcp_synack_retries
            value: 2
          - name: net.ipv4.tcp_syn_retries
            value: 3
        # - name: net.ipv4.tcp_max_orphans
        #   value: 65536
          - name: net.ipv4.tcp_fin_timeout
            value: 10
          - name: net.ipv4.tcp_keepalive_time
            value: 60
          - name: net.ipv4.tcp_keepalive_intvl
            value: 15
          - name: net.ipv4.tcp_keepalive_probes
            value: 3
        #  - name: net.core.wmem_max
        #    value: 16777216
        #  - name: net.core.rmem_max
        #    value: 16777216
        # - name: net.ipv4.tcp_rmem
        #   value: 8192 131072 16777216
        # - name: net.ipv4.tcp_wmem
        #   value: 8192 65536 16777216
          - name: net.ipv4.tcp_orphan_retries
            value: 0
          - name: net.ipv4.tcp_sack
            value: 1
        # - name: net.ipv4.tcp_available_congestion_control
        #   value: bbr
        # - name: net.core.default_qdisc
        #   value: fq
        # - name: net.ipv4.tcp_no_metrics_save
        #   value: 1
          - name: net.ipv4.ip_local_port_range
            value: 2000 65000
          - name: net.ipv4.tcp_rfc1337
            value: 1
          - name: net.ipv4.conf.all.log_martians
            value: 0
          - name: net.ipv4.conf.default.log_martians
            value: 0
          - name: net.ipv4.conf.all.accept_source_route
            value: 0
          - name: net.ipv4.conf.default.accept_source_route
            value: 0
        # - name: fs.nr_open
        #   value: 12000000
          - name: vm.swappiness
            value: 1
          - name: vm.vfs_cache_pressure
            value: 10
          - name: vm.min_free_kbytes
            value: 67584
          - name: net.core.netdev_budget
            value: 1200
          - name: net.ipv4.tcp_max_tw_buckets
            value: 1440000
          - name: net.ipv4.tcp_fastopen
            value: 3
          - name: net.ipv4.tcp_slow_start_after_idle
            value: 0
          - name: net.ipv4.tcp_mtu_probing
            value: 1

    - role: buluma.ulimit
      vars:
        ulimit_dest: /etc/security/limits.d/20-nproc.conf
        ulimit_items:
          - limit_item: nproc
            domain: '*'
            limit_type: soft
            value: 65535
          - limit_item: nproc
            domain: '*'
            limit_type: hard
            value: 65535
          - limit_item: nofile
            domain: '*'
            limit_type: soft
            value: 1048576
          - limit_item: nofile
            domain: '*'
            limit_type: hard
            value: 1048576
