---
# tasks file for postfix
- name: Install deps
  ansible.builtin.apt:
    name:
      - postfix

- name: Setup postfix config
  ansible.builtin.blockinfile:
    path: /etc/postfix/main.cf
    block: |
      #default_destination_concurrency_limit = 500
      #default_destination_recipient_limit = 500
      #initial_destination_concurrency = 50
      #fork_delay = 1s
      #in_flow_delay = 1s
      #smtpd_recipient_limit = 30000
      #mydestination =
      #mynetworks_style = host
      #fallback_transport = relay
      # для кривых корпоративных сеток, если не может правильно отрезолвить адрес внутреннего домена
      # smtp_fallback_relay = [mail.domain.tld]:25
      mailbox_size_limit = 0
      message_size_limit = 0
      virtual_mailbox_limit = 0
      mydestination = localhost.$mydomain, localhost
      virtual_alias_maps = hash:/etc/postfix/virtual
      maximal_queue_lifetime = 1d
      bounce_queue_lifetime = 5h
    owner: root
    group: root
    mode: '0644'

- name: Suppress warning verriding earlier entry
  ansible.builtin.lineinfile:
    path: /etc/postfix/main.cf
    search_string: "mydestination = $myhostname"
    state: absent

- name: Setup virtual_alias_map
  ansible.builtin.blockinfile:
    path: /etc/postfix/virtual
    block: |
      root@{{ ansible_fqdn }} root@localhost
      bitrix@{{ ansible_fqdn }} bitrix@localhost
    owner: root
    group: root
    mode: '0644'
    create: true

- name: Run postmap
  ansible.builtin.command: postmap /etc/postfix/virtual
  changed_when: false

- name: Systemd override dir
  ansible.builtin.file:
    path: /etc/systemd/system/postfix.service.d/
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Systemd override dir
  ansible.builtin.file:
    path: /etc/systemd/system/postfix@.service.d/
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Systemd override dir
  ansible.builtin.copy:
    src: override.conf
    dest: /etc/systemd/system/postfix.service.d/
    owner: root
    group: root
    mode: '0644'

- name: Systemd override dir
  ansible.builtin.copy:
    src: override.conf
    dest: /etc/systemd/system/postfix@.service.d/
    owner: root
    group: root
    mode: '0644'

- name: Restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted
    enabled: true
    daemon_reload: true
