---
- name: Set php_cron
  ansible.builtin.set_fact:
    php_cron: php
  when: php_version == php_current_default_version and user_server_sites in ['www-data']

- name: Set php_cron
  ansible.builtin.set_fact:
    php_cron: "php{{ php_version}}"
  when: user_server_sites not in ['www-data']

- name: Creating directories log
  ansible.builtin.file:
    path: "{{ logs_path_dir }}"
    state: directory
    recurse: true
    owner: "{{ user_site }}"
    group: "{{ group_user_site }}"
    mode: '0774'

- name: Adding cron job for bitrix agents the site {{ domain }}
  ansible.builtin.cron:
    name: Adding cron bitrix agents site {{ domain }}
    minute: "*"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/usr/bin/test -f {{ path_file_run_cron }} && /usr/bin/{{ php_cron }} -f {{ path_file_run_cron }} > {{ logs_path_dir }}/site_{{ domain }}_{{ logs_path_file }} 2>&1"
    user: "{{ user_site }}"
    cron_file: "bx_agent_{{ db_name }}"

- name: Adding cron job for bitrix imopenlines agents the site {{ domain }}
  ansible.builtin.cron:
    name: Adding cron bitrix imopenlines agents site {{ domain }}
    minute: "*"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/usr/bin/test -f {{ document_root }}/bitrix/tools/imopenlines/agents.php && /usr/bin/{{ php_cron }} -f {{ document_root }}/bitrix/tools/imopenlines/agents.php > /dev/null 2>&1"
    user: "{{ user_site }}"
    cron_file: "bx_agent_{{ db_name }}"

- name: Adding cron job for dev2fun optimize agents the site {{ domain }}
  ansible.builtin.cron:
    name: Adding cron dev2fun optimize agents site {{ domain }}
    minute: "*/5"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/usr/bin/test -f {{ document_root }}/bitrix/modules/dev2fun.imagecompress/console/optimize.php && /usr/bin/{{ php_cron }} -f {{ document_root }}/bitrix/modules/dev2fun.imagecompress/console/optimize.php > {{ logs_path_dir }}/site_{{ domain }}_dev2fun_optimize.log 2>&1"
    user: "{{ user_site }}"
    cron_file: "bx_agent_{{ db_name }}"

- name: Adding cron job for dev2fun convert agents the site {{ domain }}
  ansible.builtin.cron:
    name: Adding cron dev2fun convert agents site {{ domain }}
    minute: "*/5"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/usr/bin/test -f {{ document_root }}/bitrix/modules/dev2fun.imagecompress/console/convert.php && /usr/bin/{{ php_cron }} -f {{ document_root }}/bitrix/modules/dev2fun.imagecompress/console/convert.php > {{ logs_path_dir }}/site_{{ domain }}_dev2fun_convert.log 2>&1"
    user: "{{ user_site }}"
    cron_file: "bx_agent_{{ db_name }}"

- name: Adding cron job for dev2fun cache clean agents the site {{ domain }}
  ansible.builtin.cron:
    name: Adding cron dev2fun cache clean agents site {{ domain }}
    minute: "*/5"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/usr/bin/test -f {{ document_root }}/bitrix/modules/dev2fun.imagecompress/console/cache-delayed-delete.php && /usr/bin/{{ php_cron }} -f {{ document_root }}/bitrix/modules/dev2fun.imagecompress/console/cache-delayed-delete.php > {{ logs_path_dir }}/site_{{ domain }}_dev2fun_cache_clean.log 2>&1"
    user: "{{ user_site }}"
    cron_file: "bx_agent_{{ db_name }}"
