---
- name: Creating directories log
  ansible.builtin.file:
    path: "{{ logs_path_dir }}"
    state: directory
    recurse: true
    owner: "{{ user_site }}"
    group: "{{ group_user_site }}"
    mode: '0774'

- name: Adding cron job for bitrix agents the site {{ domain }}
  ansible.builtin.cron:
    name: Adding cron bitrix agents site {{ domain }}
    minute: "*"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    job: "test -f {{ path_file_run_cron }} && php -f {{ path_file_run_cron }} > {{ logs_path_dir }}/site_{{ domain }}_{{ logs_path_file }} 2>&1"
    user: "{{ user_site }}"
