---
# Pass in a comma-separated list of repos to use (e.g. "remi,epel"). Used only
# for RHEL/CentOS.
php_enablerepo: "remi,epel"

# Extra packages to install (in addition to distro-specific default lists).
php_packages_extra: []

# Default PHP version to install on Debian-based OSes (OS-specific).
php_default_version_debian: "{{ php_version }}"
php_version: "8.2"
php_set_manual: true

# PHP package state; use 'present' to make sure it's installed, or 'latest' if
# you want to upgrade or switch versions using a new repo.
php_packages_state: present

# Whether to install recommended packages. Used only for Debian/Ubuntu.
php_install_recommends: false

# Set this to false if you're not using PHP with Apache/Nginx/etc.
php_enable_webserver: false

php_fpm_default_pool_delete: true

# PHP-FPM configuration.
php_enable_php_fpm: true
php_fpm_state: started
php_fpm_handler_state: restarted
php_fpm_enabled_on_boot: true
php_fpm_pool_user: "www-data"
php_fpm_pool_group: "www-data"
php_fpm_listen: "/run/php/php{{ php_default_version_debian }}-fpm.sock"
php_fpm_listen_allowed_clients: "127.0.0.1"
php_fpm_pm_max_children: "{{ (ansible_memtotal_mb // 2) // 32 | int | abs }}"
php_fpm_pm_start_servers: 1
php_fpm_pm_min_spare_servers: 1
php_fpm_pm_max_spare_servers: 1
php_fpm_pm_max_requests: 500
php_fpm_pm_status_path: "/fpmstatus.php"
php_fpm_php_flag_display_errors: "on"
php_fpm_php_admin_value_error_log: "/var/log/php-fpm/$pool.error.log"
php_fpm_php_admin_flag_log_errors: "on"

# PHP-FPM pool configuration.
php_fpm_pools:
  - pool_name: "{{ php_version }}"
    pool_ansible.builtin.template: www.conf.j2
    pool_listen: "{{ php_fpm_listen }}"
    pool_listen_allowed_clients: "{{ php_fpm_listen_allowed_clients }}"
    pool_pm: dynamic
    pool_pm_max_children: "{{ php_fpm_pm_max_children }}"
    pool_pm_start_servers: "{{ php_fpm_pm_start_servers }}"
    pool_pm_min_spare_servers: "{{ php_fpm_pm_min_spare_servers }}"
    pool_pm_max_spare_servers: "{{ php_fpm_pm_max_spare_servers }}"
    pool_pm_max_requests: "{{ php_fpm_pm_max_requests }}"
    pool_pm_status_path: "{{ php_fpm_pm_status_path }}"
    pool_php_flag_display_errors: "{{ php_fpm_php_flag_display_errors }}"
    pool_php_admin_value_error_log: "{{ php_fpm_php_admin_value_error_log }}"
    pool_php_admin_flag_log_errors: "{{ php_fpm_php_admin_flag_log_errors }}"

# The executable to run when calling PHP from the command line.
php_executable: "php"

# OpCache settings.
php_opcache_zend_extension: "opcache.so"
php_opcache_enable: "1"
php_opcache_enable_cli: "0"
php_opcache_memory_consumption: "{{ (ansible_memtotal_mb // 8) | int | abs }}"
php_opcache_interned_strings_buffer: "{{ (ansible_memtotal_mb // 8) // 4 | int | abs }}"
php_opcache_max_accelerated_files: "100000"
php_opcache_max_wasted_percentage: "1"
php_opcache_validate_timestamps: "1"
php_opcache_revalidate_path: "0"
php_opcache_revalidate_freq: "0"
php_opcache_max_file_size: "0"
php_opcache_fast_shutdown: "1"
php_opcache_save_comments: "1"
php_opcache_load_comments: "1"
php_opcache_blacklist_filename: ""

# APCu settings.
php_enable_apc: true
php_apc_shm_size: "96M"
php_apc_enable_cli: "0"

# If this is set to false, none of the following options will have any effect.
# Any and all changes to /etc/php.d/.ini will be your responsibility.
php_use_managed_bitrixenv_ini: true

php_expose_php: "Off"
php_memory_limit: "256M"
php_max_execution_time: "300"
php_max_input_time: "300"
php_max_input_vars: "100000"
php_pcre_backtrack_limit: "1000000"
php_pcre_recursion_limit: "14000"
php_realpath_cache_size: "4096k"

php_mysql_default_socket: "/run/mysqld/mysqld.sock"
php_mysqli_default_socket: "{{ php_mysql_default_socket }}"

php_mail_add_x_header: "Off"

php_mbstring_internal_encoding: "UTF-8"

php_session_entropy_length: "128"
php_session_entropy_file: "/dev/urandom"

php_file_uploads: "On"
php_upload_max_filesize: "1024M"
php_max_file_uploads: "100"

php_post_max_size: "1024M"
php_date_timezone: "{{ timesync_timezone }}"
php_allow_url_fopen: "On"

php_sendmail_path: "sendmail -t -i"
php_output_buffering: "4096"
php_short_open_tag: "On"
php_disable_functions: []

php_session_cookie_lifetime: 604800
php_session_gc_probability: 1
php_session_gc_divisor: 1000
php_session_gc_maxlifetime: 604800
php_session_save_handler: files
php_session_save_path: "/var/lib/php/sessions/"
php_session_name: "PHPSESSID"

php_error_reporting: "E_ALL & ~E_NOTICE & ~E_DEPRECATED"
php_display_errors: "Off"
php_display_startup_errors: "Off"

php_upload_tmp_dir: "/tmp/"

# Install PHP from source (instead of using a package manager) with these vars.
php_install_from_source: false
php_use_managed_ini: false
timesync_timezone: Europe/Moscow
