# tasks file
---
- name: Groups pre
  ansible.builtin.import_tasks: groups-pre.yml
  tags:
    - configuration
    - user
    - user-groups
    - user-groups-pre

- name: Users
  ansible.builtin.import_tasks: users.yml
  tags:
    - configuration
    - user
    - user-users

- name: Groups post
  ansible.builtin.import_tasks: groups-post.yml
  tags:
    - configuration
    - user
    - user-groups
    - user-groups-post
