---
# Variable setup.
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Define nginx_user.
  ansible.builtin.set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

# Setup/install tasks.
- name: Include distro specific tasks
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "setup-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "setup-{{ ansible_distribution }}.yml"
    - "setup-{{ ansible_os_family }}.yml"

# Vhost configuration.
# - name: Include vhosts yaml[comments] noqa yaml[comments]
#  ansible.builtin.import_tasks: vhosts.yml

# Nginx setup.
# - name: Copy nginx configuration in place.
#  ansible.builtin.template:
#    src: "{{ nginx_conf_template }}"
#    dest: "{{ nginx_conf_file_path }}"
#    owner: root
#    group: "{{ root_group }}"
#    mode: 0644
#  notify:
#    - reload nginx

- name: Ensure nginx service is running as configured.
  ansible.builtin.service:
    name: nginx
    state: "{{ nginx_service_state }}"
    enabled: "{{ nginx_service_enabled }}"
