---
- name: APT | Install sury dependencies
  ansible.builtin.apt:
    name: "{{ pkgs }}"
  vars:
    pkgs:
      - apt-transport-https
      - ca-certificates
      - gpg

- name: Ensure nginx sury repo keyring is installed.
  ansible.builtin.apt:
    deb: "https://mirror.hoztnode.net/mirrors/deb.sury.org/debsuryorg-archive-keyring.deb"
    state: present
  when: nginx_ppa_use | bool

- name: Add sury repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/deb.sury.org-nginx.gpg] https://mirror.yandex.ru/mirrors/packages.sury.org/nginx-mainline/ {{ ansible_distribution_release }} main"
    state: present
    filename: deb.sury.org-nginx
  when: nginx_ppa_use | bool

- name: Ensure nginx is installed.
  ansible.builtin.apt:
    name: "{{ nginx_package_name_debian }}"
    state: present
    update_cache: true

- name: Install additional packages.
  ansible.builtin.apt:
    name: "{{ nginx_additional_package_name_debian }}"
    state: present
