---
- name: APT | Install sury dependencies
  ansible.builtin.apt:
    name: "{{ pkgs }}"
  vars:
    pkgs:
      - apt-transport-https
      - ca-certificates
      - gpg

- name: Add PPA for Nginx (if configured).
  ansible.builtin.apt_repository:
    repo: 'ppa:ondrej/nginx'
    state: present
    update_cache: true
  register: nginx_ppa_added
  when: nginx_ppa_use | bool

- name: Install nginx.
  ansible.builtin.apt:
    name: "{{ nginx_package_name_debian }}"
    state: present

- name: Install additional packages.
  ansible.builtin.apt:
    name: "{{ nginx_additional_package_name_debian }}"
    state: present
