---
- name: restart webserver # noqa name[casing]
  ansible.builtin.service:
    name: "{{ php_webserver_daemon }}"
    state: restarted
  notify: restart php-fpm
  when: php_enable_webserver

- name: restart php-fpm # noqa name[casing]
  ansible.builtin.service:
    name: "{{ php_fpm_daemon }}"
    state: "{{ php_fpm_handler_state }}"
#  when:
#    - php_fpm_state == 'started'
#    - not ansible_check_mode
