---
- name: Copy php-fpm.conf for xdebug.
  ansible.builtin.copy:
    src: "{{ php_fpm_conf_path }}/php-fpm.conf"
    dest: "{{ php_fpm_conf_path }}/php-fpm-xdebug.conf"
    remote_src: true
    force: false
    owner: root
    group: root
    mode: "0755"

- name: Change pid in php-fpm-xdebug.conf
  ansible.builtin.lineinfile:
    path: "{{ php_fpm_conf_path }}/php-fpm-xdebug.conf"
    regexp: '^pid'
    line: "pid = /run/php/php{{ php_version }}-fpm-xdebug.pid"

- name: Change error_log in php-fpm-xdebug.conf
  ansible.builtin.lineinfile:
    path: "{{ php_fpm_conf_path }}/php-fpm-xdebug.conf"
    regexp: '^error_log'
    line: "error_log = /var/log/php{{ php_version }}-fpm-xdebug.log"

- name: Change include in php-fpm-xdebug.conf
  ansible.builtin.lineinfile:
    path: "{{ php_fpm_conf_path }}/php-fpm-xdebug.conf"
    regexp: '^include'
    line: "include={{ php_fpm_conf_path }}/pool.d/*.xdebug"

- name: Create systemd for {{ php_fpm_daemon_xdebug }}.service
  ansible.builtin.template:
    src: "fpm-xdebug-systemd.j2"
    dest: "/etc/systemd/system/{{ php_fpm_daemon_xdebug }}.service"
    owner: root
    group: root
    mode: "0644"
    force: false

- name: Ensure php-fpm is started and enabled at boot (if configured).
  ansible.builtin.service:
    name: "{{ php_fpm_daemon_xdebug }}"
    state: "{{ php_fpm_state }}"
    enabled: "{{ php_fpm_enabled_on_boot }}"
  when:
    - php_enable_php_fpm_xdebug | bool


- name: Restart php-fpm # noqa name[casing]
  ansible.builtin.service:
    name: "{{ php_fpm_daemon_xdebug }}"
    state: "{{ php_fpm_handler_state }}"
    enabled: "{{ php_fpm_enabled_on_boot }}"
  when:
    - php_enable_php_fpm_xdebug | bool
