---
- name: Ensure PHP packages are installed. # noqa name[casing]
  ansible.builtin.package:
    name: "{{ php_packages + php_packages_extra }}"
    state: "{{ php_packages_state }}"
    enablerepo: "{{ php_enablerepo | default(omit, true) }}"
  notify: restart webserver
