---
__php_packages:
  - php
  - php-cli
  - php-common
  - php-bcmath
  - php-devel
  - php-fpm
  - php-gd
  - php-intl
  - php-ldap
  - php-mbstring
  - php-mcrypt
  - php-mysqlnd
  - php-opcache
  - php-pdo
  - php-pear
  - php-pecl-apcu
  - php-pecl-imagick
  - php-pecl-geoip
  - php-pecl-memcache
  - php-pecl-zip
  - php-pspell
  - php-process
  - php-soap
  - php-sodium
  - php-xml
  - php-xmlrpc

__php_webserver_daemon: "httpd"

__php_conf_paths:
  - /etc

__php_extension_conf_paths:
  - /etc/php.d

__php_apc_conf_filename: 50-apc.ini
__php_opcache_conf_filename: 10-opcache.ini
__php_fpm_daemon: php-fpm
__php_fpm_conf_path: "/etc/fpm"
__php_fpm_pool_conf_path: "/etc/php-fpm.d/www.conf"

__php_fpm_pool_user: apache
__php_fpm_pool_group: apache
