---

# Main tasks file for locales role

- name: 'INIT | Manage variables to use for our target'
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::locales'
    - 'role::locales::config'
    - 'role::locales::init'
    - 'role::locales::install'


- name: 'INSTALL | Manage installation tasks'
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/install/{{ ansible_os_family | lower }}_family.yml"
  tags:
    - 'role::locales'
    - 'role::locales::install'


- name: 'CONFIG | Manage configuration tasks'
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/config.yml"

- name: Flush_handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - 'role::locales'
    - 'role::locales::config'
    - 'role::locales::install'
