---
# tasks file for create_site
- name: Create directory of the site {{ domain }}
  ansible.builtin.file:
    state: directory
    path: "{{ path_sites }}/{{ domain }}"
    owner: "{{ user_server_sites }}"
    group: "{{ group_user_server_sites }}"
    mode: "{{ permissions_sites_dirs }}"

############## LINK MODE ##############
- name: "Mode: link"
  block:

    - name: Checking of path existence resources taken from settings
      ansible.builtin.stat:
        path: "{{ path_site_from_links }}/{{ item }}"
      register: link_source
      with_items: "{{ site_links_resources.split(',') }}"

    - name: Link creating
      ansible.builtin.file:
        src: "{{ path_site_from_links }}/{{ item.item }}"
        dest: "{{ path_sites }}/{{ domain }}/{{ item.item }}"
        state: link
      when: item.stat.exists
      with_items: "{{ link_source.results }}"

    - ansible.builtin.include_tasks: "tasks/change_owner_and_group_symbolic_links.yaml"
      vars:
        path_links: "{{ site_links_resources.split(',') }}"
        full_path: "{{ path_sites }}/{{ domain }}"

    - name: Adding index.php file for a site
      ansible.builtin.template:
        src: "site_link_tpl/index.j2"
        dest: "{{ path_sites }}/{{ domain }}/index.php"
        owner: "{{ user_server_sites }}"
        group: "{{ group_user_server_sites }}"
        mode: "{{ permissions_sites_files }}"

    - name: Extract database name from .settings.php
      shell: |
        php -r '
        $settings = include "{{ path_site_from_links }}/bitrix/.settings.php";
        echo $settings["connections"]["value"]["default"]["database"];
        '
      register: db_name_result
      changed_when: false

    - name: Set db_name variable
      set_fact:
        db_name: "{{ db_name_result.stdout }}"

  when: mode == 'link'

############## FULL MODE ##############
- name: "Mode: full"
  block:

    - name: Creating array of urls
      ansible.builtin.set_fact:
        urls: "{{ download_bitrix_install_files_new_site.split(',') }}"
      no_log: true

    - name: Downloading Bitrix scripts
      ansible.builtin.get_url:
        url: "{{ item }}"
        dest: "{{ path_sites }}/{{ domain }}"
        owner: "{{ user_server_sites }}"
        group: "{{ group_user_server_sites }}"
        mode: "{{ permissions_sites_files }}"
        timeout: "{{ timeout_download_bitrix_install_files_new_site }}"
      # ignore_errors: true
      with_items: "{{ urls }}"

    - name: Creating of downloaded file names array
      ansible.builtin.set_fact:
        file_names_download: "{{ urls | map('basename') | list }}"
      no_log: true

    - name: Generating index.html using links of downloaded files
      ansible.builtin.template:
        dest: "{{ path_sites }}/{{ domain }}/index.php"
        src: "site_full_tpl/index.j2"
        owner: "{{ user_server_sites }}"
        group: "{{ group_user_server_sites }}"
        mode: "{{ permissions_sites_files }}"
      no_log: true

    - name: Installing of python3-pymysql
      ansible.builtin.apt:
        name: python3-pymysql
        state: present

    - name: Creating database
      community.mysql.mysql_db:
        name: "{{ db_name }}"
        state: present

    - name: Creating database user
      community.mysql.mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        state: present

    - name: Creating directory bitrix/php_interface
      ansible.builtin.file:
        state: directory
        path: "{{ path_sites }}/{{ domain }}/bitrix/php_interface"
        owner: "{{ user_server_sites }}"
        group: "{{ group_user_server_sites }}"
        mode: "{{ permissions_sites_dirs }}"

    - name: Generating dbconn.php file
      ansible.builtin.template:
        dest: "{{ path_sites }}/{{ domain }}/bitrix/php_interface/dbconn.php"
        src: "site_full_tpl/dbconn.j2"
        owner: "{{ user_server_sites }}"
        group: "{{ group_user_server_sites }}"
        mode: "{{ permissions_sites_files }}"

    - name: Generate crypto key
      ansible.builtin.set_fact:
        crypto_key: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=32') }}"

    - name: Read push-server config file
      ansible.builtin.slurp:
        src: "{{ push_server_config }}"
      register: push_config_content

    - name: Extract SECURITY_KEY and set push_key variable
      ansible.builtin.set_fact:
        push_key: "{{ push_config_content['content'] | b64decode | regex_search('SECURITY_KEY=\"([^\"]+)\"', '\\1') | first }}"

    - name: Generating .settings.php file
      ansible.builtin.template:
        dest: "{{ path_sites }}/{{ domain }}/bitrix/.settings.php"
        src: "site_full_tpl/.settings.j2"
        owner: "{{ user_server_sites }}"
        group: "{{ group_user_server_sites }}"
        mode: "{{ permissions_sites_files }}"

    - name: Generating after_connect_d7.php file
      ansible.builtin.template:
        dest: "{{ document_root }}/bitrix/php_interface/after_connect_d7.php"
        src: "roles/create_site/templates/site_full_tpl/after_connect_d7.php.j2"
        owner: "{{ user_server_sites }}"
        group: "{{ group_user_server_sites }}"
        mode: "{{ permissions_sites_files }}"

    - name: Creating directory from bitrix temporary files
      ansible.builtin.file:
        state: directory
        path: "{{ bx_temporary_files_directory }}"
        owner: "{{ user_server_sites }}"
        group: "{{ group_user_server_sites }}"
        mode: "{{ permissions_sites_dirs }}"
        recurse: true
      vars:
        bx_temporary_files_directory: "{{ path_sites }}/.bx_temp/{{ db_name }}/"

    - ansible.builtin.include_tasks: "tasks/add_cron_agents.yaml"
      vars:
        path_file_run_cron: "{{ path_sites }}/{{ domain }}{{ bx_cron_agents_path_file_after_document_root }}"
        user_site: "{{ user_server_sites }}"
        group_user_site: "{{ group_user_server_sites }}"
        logs_path_dir: "{{ bx_cron_logs_path_dir }}"
        logs_path_file: "{{ bx_cron_logs_path_file }}"

  when: mode == 'full'

############## SITE FILES ##############
- name: Adding .htaccess file
  ansible.builtin.copy:
    src: "site_files/.htaccess"
    dest: "{{ path_sites }}/{{ domain }}"
    owner: "{{ user_server_sites }}"
    group: "{{ group_user_server_sites }}"
    mode: "{{ permissions_sites_files }}"

############## NGINX ##############
- name: Get Nginx version
  ansible.builtin.command: nginx -v
  register: nginx_version_output
  changed_when: false

- name: Extract Nginx version number
  ansible.builtin.set_fact:
    nginx_version: "{{ nginx_version_output.stderr | regex_search('\\d+\\.\\d+\\.\\d+') }}"

- name: Adding Nginx site_settings directory
  ansible.builtin.file:
    path: "{{ path_nginx }}/site_settings/{{ domain }}"
    state: directory
    owner: root
    group: root
    mode: '755'

- name: Adding Nginx site_settings file
  ansible.builtin.template:
    dest: "{{ path_nginx }}/site_settings/{{ domain }}/bx_temp.conf"
    src: "nginx_conf/bx_temp.j2"
    owner: root
    group: root
    mode: '644'

- name: Copying default configs to site_settings
  ansible.builtin.copy:
    src: "nginx_files/custom_conf.d/site_settings/default/*.conf"
    dest: "{{ path_nginx }}/site_settings/{{ domain }}/"
    owner: root
    group: root
    mode: '644'

- name: Copying ssl_default.conf to ssl_{{ domain }}.conf
  ansible.builtin.copy:
    src: "nginx_files/ssl_conf/ssl_default.conf"
    dest: "/etc/{{ service_nginx_name }}/ssl_conf/ssl_{{ domain }}.conf"
    owner: root
    group: root
    mode: '644'

- name: Adding Nginx configuration file
  ansible.builtin.template:
    dest: "{{ path_nginx_sites_conf }}/{{ domain }}.conf"
    src: "nginx_conf/site.j2"
    owner: root
    group: root
    mode: '644'

- name: Creating symbol link (site_enable) for Nginx configuration file
  ansible.builtin.file:
    src: "{{ path_nginx_sites_conf }}/{{ domain }}.conf"
    dest: "{{ path_nginx_sites_enabled }}/{{ domain }}.conf"
    state: link

- name: Adding Nginx site_settings directory
  ansible.builtin.file:
    path: "{{ path_nginx }}/site_settings/{{ domain }}"
    state: directory
    owner: root
    group: root
    mode: '755'

- name: Adding Nginx site_settings file
  ansible.builtin.template:
    dest: "{{ path_nginx }}/site_settings/{{ domain }}/bx_temp.conf"
    src: "roles/create_site/templates/nginx_conf/bx_temp.j2"
    owner: root
    group: root
    mode: '644'

- name: Restarting Nginx
  ansible.builtin.systemd:
    name: "{{ service_nginx_name }}"
    state: reloaded


############## APACHE ##############
- name: Adding Apache configuration file
  ansible.builtin.template:
    dest: "{{ path_apache_sites_conf }}/{{ domain }}.conf"
    src: "apache_conf/site.j2"
    owner: root
    group: root
    mode: '644'

- name: Creating symbol link (site_enable) for Apache configuration file
  ansible.builtin.file:
    src: "{{ path_apache_sites_conf }}/{{ domain }}.conf"
    dest: "{{ path_apache_sites_enabled }}/{{ domain }}.conf"
    state: link

- name: Restarting Apache
  ansible.builtin.systemd:
    name: "{{ service_apache_name }}"
    state: reloaded

############## Logrotate ##############

- name: Creating logs directory
  ansible.builtin.file:
    state: directory
    path: "{{ document_root }}/logs"
    owner: "{{ user_server_sites }}"
    group: "{{ group_user_server_sites }}"
    mode: "{{ permissions_sites_dirs }}"
    recurse: true

- name: Adding logrotate file
  ansible.builtin.template:
    src: "roles/create_site/templates/logrotate/logrotate.j2"
    dest: "/etc/logrotate.d/{{ domain }}"
    owner: "{{ user_server_sites }}"
    group: "{{ group_user_server_sites }}"
    mode: "644"
