---
- name: Restart sysfsutils
  ansible.builtin.service:
    name: sysfsutils
    state: restarted

- name: Restart redis
  ansible.builtin.service:
    name: "{{ redis_daemon }}"
    state: restarted
