---
- name: Enable remi repo for PHP "{{ php_version_redhat }}"
  ansible.builtin.set_fact:
    php_enablerepo:
      "remi,remi-php{{ php_version_redhat }}"

# See: https://github.com/ansible/ansible/issues/64852
- name: DNF module for CentOS 8+
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version | int >= 8
  block:
    - name: Ensure dnf-plugins are installed on CentOS 8+.
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present

    - name: Enable DNF module for CentOS 8+.
      ansible.builtin.shell: |
        dnf config-manager --set-enabled powertools
        dnf module enable -y php:remi-{{ php_version_redhat }}
      register: dnf_module_enable
      changed_when: "'Nothing to do' not in dnf_module_enable.stdout"
