---
nginx_user: "{{ user_server_sites }}"

nginx_service_state: started
nginx_service_enabled: true

nginx_conf_template: "nginx.conf.j2"
nginx_vhost_template: "bx_default.j2"

worker_rlimit_nofile: "10240"

nginx_worker_connections: "10240"
nginx_multi_accept: "off"

nginx_error_log: "/var/log/nginx/error.log warn"
nginx_access_log: "/var/log/nginx/access.log main buffer=16k flush=2m"

nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"
nginx_types_hash_max_size: "2048"

nginx_keepalive_timeout: "75"
nginx_keepalive_requests: "600"

nginx_server_tokens: "off"

nginx_client_max_body_size: "1024m"
nginx_client_body_buffer_size: "4m"

nginx_server_names_hash_bucket_size: "128"

nginx_listen_ipv6: true

nginx_proxy_cache_path: ""

nginx_extra_conf_options: ""
# Example extra main options, used within the main nginx's context:
#   nginx_extra_conf_options: |
#     env VARIABLE;
#     include /etc/nginx/main.d/*.conf;

# nginx_extra_http_options: ""
# Example extra http options, printed inside the main server http config:
#    nginx_extra_http_options: |
#      proxy_buffering    off;
#      proxy_set_header   X-Real-IP $remote_addr;
#      proxy_set_header   X-Scheme $scheme;
#      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
#      proxy_set_header   Host $http_host;
nginx_extra_http_options: |
  # Parameters for back-end request proxy
  proxy_connect_timeout		300;
  proxy_send_timeout		300;
  proxy_read_timeout		300;
  proxy_buffer_size		64k;
  proxy_buffers			8 256k;
  proxy_busy_buffers_size		256k;
  proxy_temp_file_write_size	10m;

  # Assign default error handlers
  error_page 500 502 503 504 /500.html;
  error_page 404 = /404.html;

  # Content compression parameters
  gzip				on;
  gzip_comp_level 4;
  gzip_proxied			any;
  gzip_static			on;
  gzip_http_version		1.0;
  gzip_types			application/atom+xml application/javascript application/json application/rss+xml application/vnd.ms-fontobject application/x-font-opentype application/x-font-truetype application/x-font-ttf application/x-javascript application/xhtml+xml application/xml font/eot font/opentype font/otf font/truetype image/svg+xml image/vnd.microsoft.icon image/x-icon image/x-win-bitmap text/css text/javascript text/plain text/xml application/xml+rss;

  fastcgi_read_timeout 300;
  fastcgi_connect_timeout 300;
  fastcgi_send_timeout 300;
  fastcgi_temp_file_write_size 10m;
  fastcgi_buffer_size 64k;
  fastcgi_buffering on;
  fastcgi_buffers 8 256k;
  fastcgi_busy_buffers_size  256k;

nginx_log_format_main: |-
  '$remote_addr - $remote_user [$time_local - $upstream_response_time] '
  '$status "$request" $body_bytes_sent '
  '"$http_referer" "$http_user_agent" "$http_x_forwarded_for"'

nginx_log_format_common: |-
  '$remote_addr - - [$time_local - $upstream_response_time] '
  '"$request" $status $bytes_sent '
  '"$http_referer" "$http_user_agent" $msec'

nginx_log_format_balancer: |-
  '$remote_addr - $remote_user [$time_iso8601] "$host" '
  '"$request" $status $body_bytes_sent "schema: $scheme" '
  '"$http_referer" "$http_user_agent" "$http_x_forwarded_for" '
  '"$request_length" : "$request_time" -> $upstream_response_time'

nginx_log_format_debug: '$upstream_response_time,"$time_local","$remote_addr","$request",$status,$body_bytes_sent'

nginx_conf_main_directory: "/etc/nginx/"
nginx_vhost_path_enabled: "/etc/nginx/bx/site_enabled/"

nginx_vhosts: []
