---
- name: Install deps
  ansible.builtin.apt:
    name:
      - lnav

- name: Create a /root/.config/lnav/ directory
  ansible.builtin.file:
    path: /root/.config/lnav/
    state: directory
    mode: '0755'

- name: Copy byobu status
  ansible.builtin.copy:
    src: "lnav/config.json"
    dest: "/root/.config/lnav/config.json"
    owner: root
    group: root
    mode: '0644'
