---
- name: Install deps
  ansible.builtin.apt:
    name:
      - bash-completion
      - bat
      - bpytop
      - colordiff
      - duf
      - exa
      - fd-find
      - fzf
      - gdu
      - lsd
      - ripgrep
  environment:
    NEEDRESTART_MODE: automatically

- name: Needrestart setup
  ansible.builtin.include_tasks: needrestart.yml

- name: Bashrc setup
  ansible.builtin.include_tasks: bashrc.yml

- name: Byobu setup
  ansible.builtin.include_tasks: byobu.yml

- name: Htop setup
  ansible.builtin.include_tasks: htop.yml

- name: Liquidprompt setup
  ansible.builtin.include_tasks: liquidprompt.yml
